#SPDX-License-Identifier: MIT-0
---
- name: Restart promtail stack
  community.docker.docker_compose_v2:
    project_src: "{{ promtail_dir }}"
    state: present
    recreate: always
    pull: missing
    remove_orphans: true