#SPDX-License-Identifier: MIT-0
---
- name: Ensure promtail directory present
  ansible.builtin.file:
    path: "{{ promtail_dir }}/config"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy promtail config
  ansible.builtin.template:
    src: promtail.yaml.j2
    dest: "{{ promtail_dir }}/config/promtail.yaml"
    owner: root
    group: root
    mode: "0644"
  notify: Restart promtail stack

- name: Deploy promtail docker-compose
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ promtail_dir }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart promtail stack

- name: Start promtail
  community.docker.docker_compose_v2:
    project_src: "{{ promtail_dir }}"
    state: present
    pull: missing
    remove_orphans: true