#SPDX-License-Identifier: MIT-0
---
nginx_conf_path: "{{ ansible_dir }}/roles/nginx/templates/nginx.conf"
nginx_conf_path_dest: /etc/nginx/nginx.conf

default_conf_template: default.j2
default_conf_path_dest: /etc/nginx/sites-available/{{ site_server_name }}.conf

nginx_pub_crt: "{{ ssl_cert_dir }}/pub.pem"
nginx_privkey: "{{ ssl_cert_dir }}/privkey.pem"

nginx_default_ufw_rules:
  - comment: nginx-http
    rule: allow
    port: "80"
    proto: tcp
    
  - comment: nginx-https
    rule: allow
    port: "443"
    proto: tcp

nginx_budget_ufw_rules: []