#SPDX-License-Identifier: MIT-0
---
nginx_conf_path: /home/kali/devops/ansible/configs/nginx/nginx.conf
default_conf_path: /home/kali/devops/ansible/configs/nginx/default

nginx_conf_path_dest: /etc/nginx/nginx.conf
default_conf_path_dest: /etc/nginx/sites-available/default

nginx_pub_crt: /var/www/ssl/pub.pem
nginx_privkey: /var/www/ssl/privkey.pem

nginx_default_ufw_rules:
  - comment: nginx-http
    rule: allow
    port: "80"
    proto: tcp
    
  - comment: nginx-https
    rule: allow
    port: "443"
    proto: tcp
