---
nginx_conf_path_dest: /etc/nginx/nginx.conf

server_name: darpir.ru
node_exporter: node_exporter
site_server_name: site.darpir.ru
budget_server_name: budget.darpir.ru
site_web_root: /var/www/html
ssl_cert_dir: /var/www/ssl
actual_port: 5006
node_exporter_public_port: 9100
node_exporter_upstream_port: 9101

allowed_ips: "{{ vault_allowed_ips | default([]) }}"

nginx_pub_crt: "{{ ssl_cert_dir }}/pub.pem"
nginx_privkey: "{{ ssl_cert_dir }}/privkey.pem"

nginx_default_ufw_rules:
  - comment: nginx-http
    rule: allow
    port: "80"
    proto: tcp
  - comment: nginx-https
    rule: allow
    port: "443"
    proto: tcp

nginx_budget_ufw_rules: []