ansible_dir: "{{ lookup('env', 'ANSIBLE_DIR') | default('/home/kali/devops/ansible', true) }}"

ssl_cert_dir: /var/www/ssl
site_server_name: site.darpir.ru
budget_server_name: budget.darpir.ru
site_web_root: /var/www/html

actual_port: 5006
actual_data_dir: /opt/actual_data
actual_version: latest

node_exporter_public_port: 9100
node_exporter_upstream_port: 9101

loki_port: 3100

allowed_ips: "{{ vault_allowed_ips | default([]) }}"