ufw_enabled: true
ufw_state: enabled
ufw_default_incoming: deny
ufw_default_outgoing: allow
ufw_logging: "on"

ufw_base_rules:
  - comment: ssh-admin
    rule: allow
    port: "22"
    proto: tcp

node_exporter_ufw_rules: >-
  {%- set rules = [] -%}
  {%- for ip in vault_allowed_ips | default([]) -%}
  {%- set _ = rules.append({
        'comment': 'node-exporter-' ~ ip,
        'rule': 'allow',
        'port': '9100',
        'proto': 'tcp',
        'from_ip': ip
      }) -%}
  {%- endfor -%}
  {{ rules }}

ufw_rules: >-
  {{
    ufw_base_rules
    + (nginx_default_ufw_rules | default([]))
    + (nginx_budget_ufw_rules | default([]))
    + (actual_budget_ufw_rules | default([]))
    + (node_exporter_ufw_rules | default([]))
  }}