---
- name: Deploy Loki and Promtail stack
  hosts: all
  become: true

  vars_files:
    - "{{ playbook_dir }}/../../vaults/allowed-ips.secrets.yaml"

  roles:
    - loki
    - promtail
    - nginx
    - ufw
