---
- name: Ensure Node exporter present
  hosts: all
  become: yes

  vars_files:
    - "{{ playbook_dir }}/../../vaults/allowed-ips.secrets.yaml"

  roles:
    - node_exporter
    - nginx
    - ufw
