---
- name: Replace ssl certificate
  hosts: all
  become: true

  vars_prompt:
    - name: privkey_src
      prompt: "Path to private key"
      private: false
    - name: pub_src
      prompt: "Path to public certificate"
      private: false

  roles:
    - replace-certificate