#SPDX-License-Identifier: MIT-0
---
- name: Restart loki stack
  community.docker.docker_compose_v2:
    project_src: "{{ loki_dir }}"
    state: present
    recreate: always
    pull: missing
    remove_orphans: true
